In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [3]:
df_mm = pd.read_csv('КластерММ.csv')
df_em = pd.read_csv('КластерЭМ.csv')

In [4]:
#Для бинарной классификации: нравится - не нравится
df_mm_bin = df_mm[df_mm['Рейтинг'] != 0]
df_em_bin = df_em[df_em['Рейтинг'] != 0]

In [17]:
df_mm['Рейтинг'] = df_mm['Рейтинг'].apply(lambda x: 1 if x > 0 else (-1 if x < 0 else x))
df_em['Рейтинг'] = df_em['Рейтинг'].apply(lambda x: 1 if x > 0 else (-1 if x < 0 else x))
df_mm_bin['Рейтинг'] = df_mm_bin['Рейтинг'].apply(lambda x: 1 if x > 0 else (-1 if x < 0 else x))
df_em_bin['Рейтинг'] = df_em_bin['Рейтинг'].apply(lambda x: 1 if x > 0 else (-1 if x < 0 else x))

In [37]:
X1 = df_mm.drop(['Рейтинг', 'Лайки', 'Дизлайки', 'Реакции', 'Текст'],axis=1)
y1 = df_mm['Рейтинг']

X2 = df_em.drop(['Рейтинг', 'Лайки', 'Дизлайки', 'Реакции', 'Текст'],axis=1)
y2 = df_em['Рейтинг']

X3 = df_mm_bin.drop(['Рейтинг', 'Лайки', 'Дизлайки', 'Реакции', 'Текст'],axis=1)
y3 = df_mm_bin['Рейтинг']

X4 = df_em_bin.drop(['Рейтинг', 'Лайки', 'Дизлайки', 'Реакции', 'Текст'],axis=1)
y4 = df_em_bin['Рейтинг']

In [38]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.3, random_state=101)
scaler = StandardScaler()
scaled_X1_train = scaler.fit_transform(X1_train)
scaled_X1_test = scaler.transform(X1_test)

X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.3, random_state=101)
scaler = StandardScaler()
scaled_X2_train = scaler.fit_transform(X2_train)
scaled_X2_test = scaler.transform(X2_test)

X3_train, X3_test, y3_train, y3_test = train_test_split(X3, y3, test_size=0.3, random_state=101)
scaler = StandardScaler()
scaled_X3_train = scaler.fit_transform(X3_train)
scaled_X3_test = scaler.transform(X3_test)

X4_train, X4_test, y4_train, y4_test = train_test_split(X4, y4, test_size=0.3, random_state=101)
scaler = StandardScaler()
scaled_X4_train = scaler.fit_transform(X4_train)
scaled_X4_test = scaler.transform(X4_test)

## Логистическая регрессия

In [15]:
import warnings
warnings.filterwarnings("ignore")

In [21]:
from sklearn.linear_model import LogisticRegression

In [39]:
model = LogisticRegression()
log_model = LogisticRegression(solver='newton-cg',multi_class="multinomial",max_iter=50)
penalty = ['l1', 'l2']
C = np.logspace(0, 4, 10)
grid_model = GridSearchCV(log_model,param_grid={'C':C,'penalty':penalty})
grid_model.fit(scaled_X1_train, y1_train)
grid_model.best_params_
y1_pred = grid_model.predict(scaled_X1_test)
print(confusion_matrix(y1_test,y1_pred))
print(classification_report(y1_test,y1_pred))

[[  0  13   0]
 [  0 683   4]
 [  0  34  11]]
              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        13
           0       0.94      0.99      0.96       687
           1       0.73      0.24      0.37        45

    accuracy                           0.93       745
   macro avg       0.56      0.41      0.44       745
weighted avg       0.91      0.93      0.91       745



In [40]:
model = LogisticRegression()
log_model = LogisticRegression(solver='newton-cg',multi_class="multinomial",max_iter=50)
penalty = ['l1', 'l2']
C = np.logspace(0, 4, 10)
grid_model = GridSearchCV(log_model,param_grid={'C':C,'penalty':penalty})
grid_model.fit(scaled_X2_train, y2_train)
grid_model.best_params_
y2_pred = grid_model.predict(scaled_X2_test)
print(confusion_matrix(y2_test,y2_pred))
print(classification_report(y2_test,y2_pred))

[[75 19 22]
 [39 20 30]
 [23 25 81]]
              precision    recall  f1-score   support

          -1       0.55      0.65      0.59       116
           0       0.31      0.22      0.26        89
           1       0.61      0.63      0.62       129

    accuracy                           0.53       334
   macro avg       0.49      0.50      0.49       334
weighted avg       0.51      0.53      0.51       334



In [41]:
model = LogisticRegression()
log_model = LogisticRegression(solver='newton-cg',multi_class="multinomial",max_iter=50)
penalty = ['l1', 'l2']
C = np.logspace(0, 4, 10)
grid_model = GridSearchCV(log_model,param_grid={'C':C,'penalty':penalty})
grid_model.fit(scaled_X3_train, y3_train)
grid_model.best_params_
y3_pred = grid_model.predict(scaled_X3_test)
print(confusion_matrix(y3_test,y3_pred))
print(classification_report(y3_test,y3_pred))

[[ 9  6]
 [12 38]]
              precision    recall  f1-score   support

          -1       0.43      0.60      0.50        15
           1       0.86      0.76      0.81        50

    accuracy                           0.72        65
   macro avg       0.65      0.68      0.65        65
weighted avg       0.76      0.72      0.74        65



In [42]:
model = LogisticRegression()
log_model = LogisticRegression(solver='newton-cg',multi_class="multinomial",max_iter=50)
penalty = ['l1', 'l2']
C = np.logspace(0, 4, 10)
grid_model = GridSearchCV(log_model,param_grid={'C':C,'penalty':penalty})
grid_model.fit(scaled_X4_train, y4_train)
grid_model.best_params_
y4_pred = grid_model.predict(scaled_X4_test)
print(confusion_matrix(y4_test,y4_pred))
print(classification_report(y4_test,y4_pred))

[[90 25]
 [46 82]]
              precision    recall  f1-score   support

          -1       0.66      0.78      0.72       115
           1       0.77      0.64      0.70       128

    accuracy                           0.71       243
   macro avg       0.71      0.71      0.71       243
weighted avg       0.72      0.71      0.71       243



## KNN

In [23]:
from sklearn.neighbors import KNeighborsClassifier

In [43]:
model = KNeighborsClassifier()
param_grid = {'n_neighbors':[1,2,3],
              'weights':['uniform', 'distance']}
grid_model = GridSearchCV(estimator=model,
                          param_grid=param_grid, cv=5)
grid_model.fit(scaled_X1_train, y1_train)
y1_pred = grid_model.predict(scaled_X1_test)
print(confusion_matrix(y1_test, y1_pred))
print(classification_report(y1_test, y1_pred))

[[  0  13   0]
 [  5 675   7]
 [  0  38   7]]
              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        13
           0       0.93      0.98      0.96       687
           1       0.50      0.16      0.24        45

    accuracy                           0.92       745
   macro avg       0.48      0.38      0.40       745
weighted avg       0.89      0.92      0.90       745



In [44]:
model = KNeighborsClassifier()
param_grid = {'n_neighbors':[1,2,3],
              'weights':['uniform', 'distance']}
grid_model = GridSearchCV(estimator=model,
                          param_grid=param_grid, cv=5)
grid_model.fit(scaled_X2_train, y2_train)
y2_pred = grid_model.predict(scaled_X2_test)
print(confusion_matrix(y2_test, y2_pred))
print(classification_report(y2_test, y2_pred))

[[65 25 26]
 [31 30 28]
 [38 34 57]]
              precision    recall  f1-score   support

          -1       0.49      0.56      0.52       116
           0       0.34      0.34      0.34        89
           1       0.51      0.44      0.47       129

    accuracy                           0.46       334
   macro avg       0.45      0.45      0.44       334
weighted avg       0.46      0.46      0.45       334



In [45]:
model = KNeighborsClassifier()
param_grid = {'n_neighbors':[1,2,3],
              'weights':['uniform', 'distance']}
grid_model = GridSearchCV(estimator=model,
                          param_grid=param_grid, cv=5)
grid_model.fit(scaled_X3_train, y3_train)
y3_pred = grid_model.predict(scaled_X3_test)
print(confusion_matrix(y3_test, y3_pred))
print(classification_report(y3_test, y3_pred))

[[ 6  9]
 [14 36]]
              precision    recall  f1-score   support

          -1       0.30      0.40      0.34        15
           1       0.80      0.72      0.76        50

    accuracy                           0.65        65
   macro avg       0.55      0.56      0.55        65
weighted avg       0.68      0.65      0.66        65



In [46]:
model = KNeighborsClassifier()
param_grid = {'n_neighbors':[1,2,3],
              'weights':['uniform', 'distance']}
grid_model = GridSearchCV(estimator=model,
                          param_grid=param_grid, cv=5)
grid_model.fit(scaled_X4_train, y4_train)
y4_pred = grid_model.predict(scaled_X4_test)
print(confusion_matrix(y4_test, y4_pred))
print(classification_report(y4_test, y4_pred))

[[79 36]
 [50 78]]
              precision    recall  f1-score   support

          -1       0.61      0.69      0.65       115
           1       0.68      0.61      0.64       128

    accuracy                           0.65       243
   macro avg       0.65      0.65      0.65       243
weighted avg       0.65      0.65      0.65       243



## SVM

In [30]:
from sklearn.svm import SVC

In [47]:
model = SVC()
param_grid = {'C':[1,5,8],'kernel':['linear','rbf']}
grid_model = GridSearchCV(model,param_grid)
grid_model.fit(scaled_X1_test, y1_test)
y1_pred = grid_model.predict(scaled_X1_test)
print(confusion_matrix(y1_test, y1_pred))
print(classification_report(y1_test, y1_pred))

[[  0  13   0]
 [  0 686   1]
 [  0  35  10]]
              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        13
           0       0.93      1.00      0.97       687
           1       0.91      0.22      0.36        45

    accuracy                           0.93       745
   macro avg       0.61      0.41      0.44       745
weighted avg       0.92      0.93      0.91       745



In [48]:
model = SVC()
param_grid = {'C':[1,5,8],'kernel':['linear','rbf']}
grid_model = GridSearchCV(model,param_grid)
grid_model.fit(scaled_X2_test, y2_test)
y2_pred = grid_model.predict(scaled_X2_test)
print(confusion_matrix(y2_test, y2_pred))
print(classification_report(y2_test, y2_pred))

[[ 91   4  21]
 [ 17  44  28]
 [ 17   9 103]]
              precision    recall  f1-score   support

          -1       0.73      0.78      0.76       116
           0       0.77      0.49      0.60        89
           1       0.68      0.80      0.73       129

    accuracy                           0.71       334
   macro avg       0.73      0.69      0.70       334
weighted avg       0.72      0.71      0.71       334



In [49]:
model = SVC()
param_grid = {'C':[1,5,8],'kernel':['linear','rbf']}
grid_model = GridSearchCV(model,param_grid)
grid_model.fit(scaled_X3_test, y3_test)
y3_pred = grid_model.predict(scaled_X3_test)
print(confusion_matrix(y3_test, y3_pred))
print(classification_report(y3_test, y3_pred))

[[14  1]
 [ 1 49]]
              precision    recall  f1-score   support

          -1       0.93      0.93      0.93        15
           1       0.98      0.98      0.98        50

    accuracy                           0.97        65
   macro avg       0.96      0.96      0.96        65
weighted avg       0.97      0.97      0.97        65



In [50]:
model = SVC()
param_grid = {'C':[1,5,8],'kernel':['linear','rbf']}
grid_model = GridSearchCV(model,param_grid)
grid_model.fit(scaled_X4_test, y4_test)
y4_pred = grid_model.predict(scaled_X4_test)
print(confusion_matrix(y4_test, y4_pred))
print(classification_report(y4_test, y4_pred))

[[ 92  23]
 [ 27 101]]
              precision    recall  f1-score   support

          -1       0.77      0.80      0.79       115
           1       0.81      0.79      0.80       128

    accuracy                           0.79       243
   macro avg       0.79      0.79      0.79       243
weighted avg       0.79      0.79      0.79       243



## DesTree

In [51]:
from sklearn.tree import DecisionTreeClassifier

In [52]:
model = DecisionTreeClassifier()
param_grid = {'criterion':['gini', 'entropy', 'log_loss']}
grid_model = GridSearchCV(model,param_grid)
grid_model.fit(scaled_X1_train, y1_train)
base_pred1 = grid_model.predict(scaled_X1_test)
print(confusion_matrix(y1_test, base_pred1))
print(classification_report(y1_test, base_pred1))

[[  2  11   0]
 [ 14 641  32]
 [  2  31  12]]
              precision    recall  f1-score   support

          -1       0.11      0.15      0.13        13
           0       0.94      0.93      0.94       687
           1       0.27      0.27      0.27        45

    accuracy                           0.88       745
   macro avg       0.44      0.45      0.44       745
weighted avg       0.88      0.88      0.88       745



In [53]:
model = DecisionTreeClassifier()
param_grid = {'criterion':['gini', 'entropy', 'log_loss']}
grid_model = GridSearchCV(model,param_grid)
grid_model.fit(scaled_X2_train, y2_train)
base_pred2 = grid_model.predict(scaled_X2_test)
print(confusion_matrix(y2_test, base_pred2))
print(classification_report(y2_test, base_pred2))

[[55 29 32]
 [18 43 28]
 [25 33 71]]
              precision    recall  f1-score   support

          -1       0.56      0.47      0.51       116
           0       0.41      0.48      0.44        89
           1       0.54      0.55      0.55       129

    accuracy                           0.51       334
   macro avg       0.50      0.50      0.50       334
weighted avg       0.51      0.51      0.51       334



In [54]:
model = DecisionTreeClassifier()
param_grid = {'criterion':['gini', 'entropy', 'log_loss']}
grid_model = GridSearchCV(model,param_grid)
grid_model.fit(scaled_X3_train, y3_train)
base_pred3 = grid_model.predict(scaled_X3_test)
print(confusion_matrix(y3_test, base_pred3))
print(classification_report(y3_test, base_pred3))

[[ 9  6]
 [19 31]]
              precision    recall  f1-score   support

          -1       0.32      0.60      0.42        15
           1       0.84      0.62      0.71        50

    accuracy                           0.62        65
   macro avg       0.58      0.61      0.57        65
weighted avg       0.72      0.62      0.64        65



In [55]:
model = DecisionTreeClassifier()
param_grid = {'criterion':['gini', 'entropy', 'log_loss']}
grid_model = GridSearchCV(model,param_grid)
grid_model.fit(scaled_X4_train, y4_train)
base_pred4 = grid_model.predict(scaled_X4_test)
print(confusion_matrix(y4_test, base_pred4))
print(classification_report(y4_test, base_pred4))

[[60 55]
 [40 88]]
              precision    recall  f1-score   support

          -1       0.60      0.52      0.56       115
           1       0.62      0.69      0.65       128

    accuracy                           0.61       243
   macro avg       0.61      0.60      0.60       243
weighted avg       0.61      0.61      0.61       243

